import { MyButton } from "mybutton.slint"; //Importa el botón
import { Styles } from "styles.slint"; //Importa los estilos

export component MyApp { //La app en sí, todo lo que se ve en pantalla
    width: 400px; //Ancho de la app
    height: 270px; //Altura de la app
    
    property <int> count: 0; //Variable, por así decirlo (propiedad tipo entero), contador inicializado en 0

    Rectangle { //Rectángulo
        border-width: 5px; //Ancho de los bordes
        border-radius: 18px; //Que tanto se redondean las esquinas
        border-color: Styles.fun-gradient; //Color del borde, importado de Styles
    }

    HorizontalLayout { //Layout horizontal
        for i in 5: Image { //Ciclo que itera la imagen 5 veces
            source: @image-url("slintLogo.svg"); //Dirección de la imagen
            width: root.width / 5; //Ancho de la imagen, dividido entre 5
            colorize: white;
            //height: 60px;
        }
    }

    HorizontalLayout { //Layout horizontal
        for i in 5: Image { //Ciclo que itera la imagen 5 veces
            source: @image-url("slintLogo.svg"); //Dirección de la imagen
            width: count > i ? root.width / 5 : 0; //Ancho de la imagen, si el contador es mayor a i, entonces el ancho es el ancho de la raíz dividido entre 5, si no, es 0
            colorize: green;
            opacity: count > i ? 1 : 0.2; //Opacidad de la imagen, si el contador es mayor a i, entonces la opacidad es 1, si no, es 0.2

            animate opacity { //Animación de la opacidad
                 duration: 150ms; //Duración de la animación
            }
        }
    }

    Text { //Texto dentro de Rectangle, la app en sí
        y: Styles.margin; //Posición en y del texto, lo posiciona en la parte superior de la app
        font-size: 26px; //Tamaño de la fuente
        text: "Rate My Demo";
    }

    MyButton { //Botón funcional de la app
        y: root.height - self.height - Styles.margin; //Posición en y del botón, lo posiciona en la parte inferior de la app

        label: "+"; //Texto del botón

        clicked => { //Función que se ejecuta al hacer clic en el botón
            if (count < 5){
                count += 1;
            } else{
                count = 0;
            }
        }
    }
}