export global Styles { //Estilos globales para la app
    //Out property es una propiedad que se puede usar en otros componentes, por así decirlo
    out property <length> margin: 16px; //Margen que pueden usar otros componentes
    out property <brush> fun-gradient: @linear-gradient(0deg, #d2ff52 0%,#91e842 70%); //Degradado que pueden usar otros componentes

    out property <brush> welcomeGradient: @linear-gradient(0deg, #6a95b3 20%, #364d7b 70%); //Degradado para la pantalla de bienvenida
}