import { LineEdit, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { Styles } from "../styles/styles.slint";
import { botonPrincipal } from "../components/boton-prinicipal.slint";
import { inputRegistro } from "../components/input-registro.slint";

export component login inherits Rectangle {
    
    callback go_to_register;

    property <string> email: "";
    property <string> pswd: "";

    property <string> empty_error: "";
    property <color> empty_error_text_color: #ff0000;
    property <color> input_border_color: #e8e8e8;

    height: 836px;
    width: 425px;

    background: Styles.blanco;

    VerticalLayout {
        padding: 30px;
        spacing: 32px;
        y: 10px;

        Rectangle {
            height: 280px;
            Text {
                text: "Faena";
                font-size: 96px;
                font-weight: Styles.black;
                font-family: "Source Sans Pro";
                color: Styles.azul-fuerte;
                height: parent.height;
                width: parent.width;
                horizontal-alignment: center;
                vertical-alignment: top;
            }
            Rectangle {
                y: 40px;
                Image {
                    height: 177px;
                    width: 177px;
                    source: @image-url("../img/FAENApng.png");
                }
            }
            Rectangle {
                y: 40px;
                Text {
                    text: "Regístrate o inicia sesión en la app para unirte a la Faenation";
                    horizontal-alignment: center;
                    vertical-alignment: bottom;
                    height: parent.height;
                    width: parent.width;
                    font-size: 20px;
                    color: Styles.azul-bajo;
                    font-weight: Styles.bold;
                }
            }
        }

        //Iniciar Sesión (Correo Electrónico)
        VerticalLayout {
            spacing: 30px;
            padding-top: 50px;

            //Iniciar Sesión (Correo Electrónico)
            inputRegistro {
                texto <=> root.email;
                placeholder: "Correo electronico";
                tipo: text;
            }

            //Iniciar Sesión (Contraseña)
            inputRegistro {
                texto <=> root.pswd;
                placeholder: "Contraseña";
                tipo: password;
            }
            //Errores
            Rectangle {
                height: 15px;
                background: transparent;
                Text {
                    text: root.empty_error;
                    color: root.empty_error_text_color;
                    horizontal-alignment: center;
                    font-size: 16px;
                    font-weight: Styles.semibold;
                    width: parent.width;
                }
            }
            //Botón Iniciar Sesión
            HorizontalLayout {
                alignment: center;
                botonPrincipal {
                    texto: "Iniciar sesión";
                    click => {
                            if (root.email == "" || root.pswd == "") {
                                root.empty_error = "Usuario y/o contraseña incorrectos";
                                root.empty_error_text_color = #ff0000;
                                root.input_border_color = #ff0000;
                            } 
                            else {
                                root.empty_error = "Login exitoso";
                                root.empty_error_text_color = #00aa00;
                                root.input_border_color = #00aa00;
                            } 
                        }
                }
            }

            //Link a registro
            VerticalLayout {
                spacing: 10px;
                Text {
                    text: "¿Aún no tienes cuenta?";
                    height: 18px;
                    font-size: 20px;
                    color: Styles.negro;
                    font-weight: Styles.semibold;
                    horizontal-alignment: left;
                }

                TouchArea {
                    height: 18px;

                    clicked => { 
                        root.go_to_register(); 
                    }

                    Text {
                        width: parent.width;
                        height: 18px;
                        text: "Crear una cuenta";
                        font-size: 20px;
                        font-weight: Styles.semibold;
                        color: Styles.azul-verde;
                        horizontal-alignment: left;        
                    }
                }
            }
        }
    }
}