import { LineEdit, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { Styles } from "../styles/styles.slint";
import { botonPrincipal } from "../components/boton-prinicipal.slint";
export component login inherits Rectangle {
    
    callback go_to_register;

    property <string> email: "";
    property <string> pswd: "";

    property <string> empty_error: "";
    property <color> empty_error_text_color: #ff0000;
    property <color> input_border_color: #e8e8e8;

    height: 836px;
    width: 425px;

    background: Styles.blanco;

    VerticalLayout {
        padding: 30px;
        spacing: 32px;
        y: 10px;

        Rectangle {
            height: 280px;
            Text {
                text: "Faena";
                font-size: 96px;
                font-weight: Styles.black;
                font-family: "Source Sans Pro";
                color: Styles.azul-fuerte;
                height: parent.height;
                width: parent.width;
                horizontal-alignment: center;
                vertical-alignment: top;
            }
            Rectangle {
                y: 40px;
                Image {
                    height: 177px;
                    width: 177px;
                    source: @image-url("../img/FAENApng.png");
                }
            }
            Rectangle {
                y: 40px;
                Text {
                    text: "Regístrate o inicia sesión en la app para unirte a la Faenation";
                    horizontal-alignment: center;
                    vertical-alignment: bottom;
                    height: parent.height;
                    width: parent.width;
                    font-size: 20px;
                    color: Styles.azul-bajo;
                    font-weight: Styles.bold;
                }
            }
        }

        //Iniciar Sesión (Correo Electrónico)
        VerticalLayout {
            spacing: 30px;
            padding-top: 30px;
            //Errores
            Rectangle {
                height: 15px;
                background: transparent;
                Text {
                    text: root.empty_error;
                    color: root.empty_error_text_color;
                    horizontal-alignment: left;
                    font-size: 10px;
                    font-weight: 500;
                    width: parent.width;
                }
            }

            //Iniciar Sesión (Correo Electrónico)
            HorizontalBox { //box para centrar el contenido
                alignment: center;
            Rectangle {
                width: 272px;
                height: 40px;
                border-width: 2px;
                border-color: Styles.gris;
                border-radius: 10px;
                background: #c5c5c5;
                /*Text {
                    text: "Correo electrónico";
                    font-size: 16px;
                    color: #e8e8e8;
                }*/

                LineEdit {
                    text <=> root.email;
                    width: 100%;
                    height: 40px;
                    font-size: 16px;
                    horizontal-alignment: center;
                    placeholder-text: "Correo electrónico";
                    input-type: text;
                }
            }
            }

            //Iniciar Sesión (Contraseña)
            HorizontalBox { //box para centrar el contenido
                alignment: center;
            Rectangle {
                width: 272px;
                height: 40px;
                border-width: 2px;
                border-color: Styles.gris;
                border-radius: 10px;
                background: #c5c5c5;

                /*Text {
                    text: "Contraseña";
                    font-size: 16px;
                    color: #e8e8e8;
                }*/

                LineEdit {
                    text <=> root.pswd;
                    width: 100%;
                    height: 40px;
                    font-size: 16px;
                    horizontal-alignment: center;
                    placeholder-text: "Contraseña";
                    input-type: password;
                }
            }
            }
            Rectangle {
                background: transparent;
                height: 20px;
            }

            //Botón Iniciar Sesión
            HorizontalBox {
                alignment: center;

                botonPrincipal {}
            }
            
            /*VerticalLayout {
                padding-left: 30px;
                padding-right: 30px;
                botonPrincipal {
                    click => {
                            if (root.email == "" || root.pswd == "") {
                                root.empty_error = "Usuario y/o contraseña incorrectos";
                                root.empty_error_text_color = #ff0000;
                                root.input_border_color = #ff0000;
                            } 
                            else {
                                root.empty_error = "Login exitoso";
                                root.empty_error_text_color = #00aa00;
                                root.input_border_color = #00aa00;
                            } 
                        }
                }
            }*/

            //Link a registro
            VerticalLayout {

                Text {
                    text: "¿Aún no tienes cuenta?";
                    height: 18px;
                    font-size: 14px;
                    color: black;
                    font-weight: 500;
                    horizontal-alignment: left;
                }

                TouchArea {
                    height: 18px;

                    clicked => { 
                        root.go_to_register(); 
                    }

                    Text {
                        width: parent.width;
                        height: 18px;
                        text: "Crear una cuenta";
                        font-size: 14px;
                        font-weight: 500;
                        color: #6a95b3;
                        horizontal-alignment: left;
                    }
                }
            }
        }
    }
}