import { LineEdit, VerticalBox } from "std-widgets.slint";

export component register inherits Rectangle {

    callback go_to_login;

    property <string> username: "";
    property <string> email: "";
    property <string> pswd: "";
    property <string> confirm_pswd: "";

    property <string> empty_error: "";
    property <color> empty_error_text_color: #ff0000;
    property <color> input_border_color: #e8e8e8;

    width: 360px;
    height: 640px;

    background: white;

    VerticalLayout {
        padding: 30px;
        spacing: 20px;

        Rectangle {
            height: 280px;
            background: white;

            Text {
                text: "Faena";
                font-size: 65px;
                font-weight: 900;
                font-family: "Source Sans Pro";
                color: #364d7b;
                height: parent.height;
                width: parent.width;
                horizontal-alignment: center;
                vertical-alignment: top;
            }

            Image {
                source: @image-url("../img/FAENApng.png");
            }

            Text {
                text: "Crea una cuenta para unirte a la Faenation";
                horizontal-alignment: center;
                vertical-alignment: bottom;
                height: parent.height;
                width: parent.width;
                font-size: 16px;
                color: #6a95b3;
                font-weight: 500;
            }
        }

        VerticalLayout {
            spacing: 4px;

            //Errores
            Rectangle {
                background: transparent;

                Text {
                    text: root.empty_error;
                    color: root.empty_error_text_color;
                    horizontal-alignment: left;
                    font-size: 10px;
                    font-weight: 500;
                    width: parent.width;
                }
            }

            //Registrarse (Nombre de Usuario)
            Rectangle {
                height: 40px;
                border-width: 2px;
                border-color: root.input_border_color;
                border-radius: 10px;
                background: #b5b8bb;

                /*Text {
                    text: "Nombre de Usuario";
                    font-size: 16px;
                    color: #e8e8e8;
                }*/

                LineEdit {
                    text <=> root.username;
                    width: 100%;
                    height: 40px;
                    font-size: 16px;
                    horizontal-alignment: center;
                    placeholder-text: "Nombre de Usuario";
                    input-type: text;
                }
            }

            //Registrarse (Correo Electrónico)
            Rectangle {
                height: 40px;
                border-width: 2px;
                border-color: root.input_border_color;
                border-radius: 10px;
                background: #b5b8bb;

                /*Text {
                    text: "Correo Electrónico";
                    font-size: 16px;
                    color: #e8e8e8;
                }*/

                LineEdit {
                    text <=> root.email;
                    width: 100%;
                    height: 40px;
                    font-size: 16px;
                    horizontal-alignment: center;
                    placeholder-text: "Correo Electrónico";
                    input-type: text;
                }
            }

            //Registrarse (Contraseña)
            Rectangle {
                height: 40px;
                border-width: 2px;
                border-color: root.input_border_color;
                border-radius: 10px;
                background: #b5b8bb;

                /*Text {
                    text: "Contraseña";
                    font-size: 16px;
                    color: #e8e8e8;
                }*/

                LineEdit {
                    text <=> root.pswd;
                    width: 100%;
                    height: 40px;
                    font-size: 16px;
                    horizontal-alignment: center;
                    placeholder-text: "Contraseña";
                    input-type: password;
                }
            }

            //Registrarse (Confirmar Contraseña)
            Rectangle {
                height: 40px;
                border-width: 2px;
                border-color: root.input_border_color;
                border-radius: 10px;
                background: #b5b8bb;

                /*Text {
                    text: "Confirmar Contraseña";
                    font-size: 16px;
                    color: #e8e8e8;
                }*/

                LineEdit {
                    text <=> root.confirm_pswd;
                    width: 100%;
                    height: 40px;
                    font-size: 16px;
                    horizontal-alignment: center;
                    placeholder-text: "Confirmar Contraseña";
                    input-type: password;
                }
            }

            Rectangle {
                height: 10px;
                background: transparent;
            }

            //Botón Registro
            VerticalLayout {
                padding-left: 30px;
                padding-right: 30px;

                Rectangle {
                    height: 40px;
                    background: #6a95b3;
                    border-radius: 10px;
                    drop-shadow-color: black;
                    drop-shadow-blur: 4px;
                    padding-left: 20px;
                    padding-right: 20px;

                    TouchArea {
                        clicked => { 
                            if (root.username == "" || root.email == "" || root.pswd == "" || root.confirm_pswd == "") {
                                root.empty_error = "No puede haber campos vacíos";
                                root.empty_error_text_color = #ff0000;
                                root.input_border_color = #ff0000;
                            }
                            else if (root.pswd != root.confirm_pswd) {
                                root.empty_error = "Las contraseñas no coinciden";
                                root.empty_error_text_color = #ff0000;
                                root.input_border_color = #ff0000;
                            }
                            else {
                                root.empty_error = "Cuenta creada exitosamente";
                                root.empty_error_text_color = #00aa00;
                                root.input_border_color = #00aa00;
                            }
                        }

                        Text {
                            text: "Crear Cuenta";
                            color: black;
                            font-size: 16px;
                            font-weight: 700;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                        }
                    }
                }
            }

            //Link a login
            VerticalLayout {

                Text {
                    text: "¿Ya tienes cuenta?";
                    font-size: 14px;
                    color: black;
                    font-weight: 500;
                }

                TouchArea {
                    height: 18px;

                    clicked => { 
                        root.go_to_login(); 
                    }

                    Text {
                        text: "Iniciar sesión";
                        font-size: 14px;
                        font-weight: 500;
                        color: #6a95b3;
                        horizontal-alignment: left;
                        width: parent.width;
                    }
                }
            }
        }
    }
}