import { Styles } from "../styles/styles.slint";
import { VerticalBox } from "std-widgets.slint";
export component welcomeFaena inherits Rectangle {

    callback go_to_login;

    height: 836px;
    width: 425px;
    background: Styles.welcomeGradient;

    VerticalLayout {
        padding: 16px;
        y: 60px;
        Rectangle { //bienvenido a faena text
            height: 200px;
            Text {
                text: "Bienvenido";
                font-size: 70px;
                width: parent.width;
                height: parent.height;
                font-weight: Styles.black;
                vertical-alignment: top;
                color: Styles.blanco;
            }

            Rectangle {
                width: parent.width;
                height: 80px;

                Text {
                    text: "a Faena";
                    font-size: 70px;
                    color: Styles.blanco;
                    font-weight: Styles.black;
                    vertical-alignment: top;
                    height: parent.height;
                    width: parent.width;
                }
            }
        }

        Rectangle { //sub texto
            height: 290px;
            //background: green;

            Text {
                text: "La plataforma que te otorga votaciones digitales de forma segura";
                height: parent.height;
                width: parent.width;
                font-size: 36px;
                font-weight: Styles.bold;
                letter-spacing: 1px;
                vertical-alignment: top;
                color: Styles.platino;
            }
        }

        HorizontalLayout {
            alignment: end;

            Rectangle {
                y: 130px;
                height: 56px;
                width: 128px;
                border-radius: 50px;
                background: white;
                drop-shadow-color: black;
                drop-shadow-blur: 4px;

                Text {
                    text: "Siguiente";
                    color: Styles.azul-fuerte;
                    font-size: 16px;
                    font-weight: Styles.bold;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                }

                TouchArea {

                    clicked => {
                        root.go_to_login();
                    }
                }
            }
        }
    }
}